modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="Apache 2.0"
[[mods]] #mandatory
modId="alwaysdroplootforge" #mandatory
version="0.2.0-RELEASE"
displayName="Always Drop Loot[Forge]" #mandatory
credits="Thanks to sargunv for the original code making this port possible!"
authors="Calamitous_End, sargunv" #optional
description='''
A 1.17+ Forge Port of sargunv's Always Drop Loot mod.
'''
[[dependencies.alwaysdroplootforge]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[37,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.alwaysdroplootforge]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17.1,)"
   ordering="NONE"
   side="BOTH"
